# Set the name of the workflow
name: Angular CICD

# Set trigger of this workflow to "works everytime someone push on docker branch"
on:
  push:
    branches: [ docker ]

# Jobs that will run on this workflow (build, deploy)
jobs:
  build:
    # Set the runner machine to ubuntu using latest version.
    runs-on: ubuntu-latest
    # Set strategy for building using node version 14.X can add another version for multi-build later
    strategy:
      matrix:
        node-version: [14.x]
    # Steps that will run on "build" job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Docker login 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "----- DOCKER LOGIN -----"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Docker Building
      run: |
        echo "----- DOCKER BUILD -----"
        docker build -t cicd/frontend:latest .
    
    - name: Docker tagging
      run: |
        echo "----- DOCKER TAG -----"
        docker tag cicd/frontend:latest sharkthovenzart/seniorproject:frontend
        
    - name: Docker push
      run: |
        echo "----- DOCKER PUSH -----"
        docker push sharkthovenzart/seniorproject:frontend
        
    - name: Docker logout
      run: |
        echo "----- DOCKER LOGOUT -----"
        docker logout
        
  # Deploy Job
  deploy:
    # Set required step "build" job must passed and finished first
    needs: build
    # Set the runner machine to ubuntu using latest version.
    runs-on: ubuntu-latest
    
    # Step that will run on "deploy" job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: SSH into Azure Virtual machine using SSH key
      uses: appleboy/ssh-action@master
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VM_PORT }}
        envs: DOCKER_USER, DOCKER_PASSWORD
        script: |
          echo "Im in AZURE VM"
          echo "----- DOCKER LOGIN -----"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo ""
          echo "----- DOCKER PULL -----"
          docker image prune -f
          docker pull docker.io/sharkthovenzart/seniorproject:frontend
          echo ""
          echo "----- DOCKER RUN -----"
          docker rm frontend --force
          docker run --name frontend -p 80:80 -d sharkthovenzart/seniorproject:frontend
          echo ""
          echo "----- DOCKER LOGOUT -----"
          docker logout
          echo ""
      
    - name: Checking contaniner and status
      env:
        VM_IP: ${{ secrets.VM_IP }}
      run: |
        echo "----- DOCKER LIST CONTAINER -----"
        docker ps -a
        echo ""
        echo "----- CURL THE SITE -----"
        curl $VM_IP:80
        echo ""
